import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "./gradients.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ahsing = localFont({
  src: "./fonts/Ahsing/ahsing-regular.otf",
  variable: "--font-ahsing",
  weight: "400",
});

export const metadata = {
  title: "Musafir",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ahsing.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
