import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "./gradients.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ahsing = localFont({
  src: "./fonts/Ahsing/Ahsing-Regular.otf",
  variable: "--font-ahsing",
  weight: "400",
});

const bricolage = localFont({
  src: [
    { path: "./fonts/BricolageGrotesque/BricolageGrotesque-ExtraLight.ttf", weight: "200" },
    { path: "./fonts/BricolageGrotesque/BricolageGrotesque-Light.ttf", weight: "300" },
    { path: "./fonts/BricolageGrotesque/BricolageGrotesque-Regular.ttf", weight: "400" },
    { path: "./fonts/BricolageGrotesque/BricolageGrotesque-Medium.ttf", weight: "500" },
    { path: "./fonts/BricolageGrotesque/BricolageGrotesque-SemiBold.ttf", weight: "600" },
    { path: "./fonts/BricolageGrotesque/BricolageGrotesque-Bold.ttf", weight: "700" },
    { path: "./fonts/BricolageGrotesque/BricolageGrotesque-ExtraBold.ttf", weight: "800" },
  ],
  variable: "--font-bricolage",
});


export const metadata = {
  title: "Musafir",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ahsing.variable} ${bricolage.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
